// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webtemp_api.Models;

#nullable disable

namespace webtemp_api.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20240717070447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("webtemp_api.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CourseID");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("webtemp_api.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnrollmentID"));

                    b.Property<int>("CourseID")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("StuInfoID")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentID");

                    b.HasIndex("CourseID");

                    b.HasIndex("StuInfoID");

                    b.ToTable("Enrollment", (string)null);
                });

            modelBuilder.Entity("webtemp_api.Models.StuInfo", b =>
                {
                    b.Property<int>("Stuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasComment("主键");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Stuid"));

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Stuname")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("名称");

                    b.Property<string>("Stusex")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("性别");

                    b.HasKey("Stuid");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("webtemp_api.Models.Enrollment", b =>
                {
                    b.HasOne("webtemp_api.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webtemp_api.Models.StuInfo", "StuInfo")
                        .WithMany("Enrollments")
                        .HasForeignKey("StuInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("StuInfo");
                });

            modelBuilder.Entity("webtemp_api.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("webtemp_api.Models.StuInfo", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
